import puppeteer from 'puppeteer-core';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,existsSync,mkdirSync} from 'node:fs';
import path from 'node:path';
const types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2','.xml':'application/xml'};
const server=createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),file=path.join(process.cwd(),'dist',decodeURIComponent(u.pathname),u.pathname.endsWith('/')?'index.html':'');try{res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(readFileSync(file));}catch{res.writeHead(404);res.end('Not found');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`;
const executablePath=process.env.BROWSER_EXECUTABLE||['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome','/usr/bin/google-chrome','/usr/bin/chromium'].find(existsSync);
assert(executablePath,'Set BROWSER_EXECUTABLE to an installed Chrome/Chromium.');
const browser=await puppeteer.launch({executablePath,headless:true});
const p=await browser.newPage();const errors=[],missing=[];
p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().startsWith(origin)&&r.status()>=400)missing.push(r.url());});
const go=route=>p.goto(origin+route,{waitUntil:'load'}),wait=ms=>new Promise(r=>setTimeout(r,ms));
const langs=['en','ko','de','ja','fr'],pages=['lab','knowledge','tracker'];
const route=(l,page)=>l==='en'?(page==='lab'?'/':`/projects/${page}/`):page==='lab'?`/${l}/lab/`:`/${l}/projects/${page}/`;
const out=process.env.QA_OUTPUT||'test-results';mkdirSync(out,{recursive:true});
try{
 await p.setJavaScriptEnabled(false);
 for(const l of langs){await go(route(l,'knowledge'));const original=readFileSync(`tests/fixtures/knowledge-${l}.html`,'utf8');const result=await p.evaluate(original=>{
  const parsed=new DOMParser().parseFromString('<main>'+original+'</main>','text/html').querySelector('main');
  const guide=document.querySelector('#get-started');if(guide)guide.remove();const currentCTA=document.querySelector('[data-quick-start]');const originalCTA=parsed.querySelector('.hero .actions a.button');currentCTA.replaceWith(originalCTA.cloneNode(true));const currentMini=document.querySelector('.mini-hanji'),oldMini=parsed.querySelector('.mini-hanji');currentMini.querySelector('figcaption').replaceWith(oldMini.querySelector('figcaption').cloneNode(true));currentMini.querySelector('[data-knowledge-controls]')?.remove();document.querySelectorAll('main script[type=module]').forEach(s=>s.remove());
  function shape(n){if(n.nodeType===3){const s=n.textContent.replace(/\s+/g,' ').trim();return s?'#text':null;}if(n.nodeType!==1)return null;return [n.tagName,[...n.attributes].map(a=>[a.name,a.value]).sort((a,b)=>a[0].localeCompare(b[0])),[...n.childNodes].map(shape).filter(x=>x!==null)];}
  return {old:[...parsed.childNodes].map(shape).filter(Boolean),current:[...document.querySelector('main').childNodes].map(shape).filter(Boolean)};
 },original);assert.deepEqual(result.current,result.old,`Knowledge ${l}: original structure preserved with revised copy, quickstart insertion and CTA`);console.log('Knowledge editorial structure preserved:',l);}
 await go('/projects/tracker/');assert.equal((await p.$$('.tm-card[data-state=review]')).length,4);assert.equal(await p.$eval('.illustration-controls',e=>getComputedStyle(e).display),'none');assert(await p.$eval('.illustration-summary',e=>e.getBoundingClientRect().height>20));console.log('No-JavaScript: complete, readable static story');
 await p.setJavaScriptEnabled(true);
 for(const width of [1440,768,390,320]){await p.setViewport({width,height:1000});for(const l of langs)for(const page of pages){await go(route(l,page));await wait(80);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${l}/${page}: overflow at ${width}`);assert.equal(await p.$eval('html',e=>e.lang),l);assert.equal(await p.$eval('link[rel=canonical]',e=>new URL(e.href).pathname),route(l,page));await p.click('.lang-picker summary');await wait(180);assert(await p.$eval('.lang-picker .lang-menu',e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth}),`${l}/${page}: language menu bounds ${width}`);assert.equal((await p.$$('.lang-picker a')).length,4);await p.keyboard.press('Escape');assert(await p.$eval('.lang-picker',e=>!e.open));assert(await p.$eval('.lang-picker summary',e=>e===document.activeElement));if(width===320){await p.click('.family-projects summary');await wait(180);assert(await p.$eval('.family-menu',e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth}));await p.keyboard.press('Escape');}console.log(`${l}/${page} ${width}: layout + localized chrome passed`);if([1440,390].includes(width)&&l==='en'){if(page==='tracker')await p.click('[data-story-step="6"]');await p.evaluate(()=>{document.activeElement?.blur();scrollTo({top:0,behavior:'instant'});});await wait(450);await p.screenshot({path:path.join(out,`astro-${page}-${width}.png`)});}}}
 for(const l of langs){await go('/'+l+'/?legacy=true#review');await p.waitForFunction(()=>!/^\/(en|ko|de|ja|fr)\/$/.test(location.pathname));assert.equal(new URL(p.url()).pathname,route(l,'knowledge'));assert(p.url().endsWith('?legacy=true#review'));}console.log('All five legacy aliases preserve query + hash');
 for(const [page,anchor] of [['lab','about'],['knowledge','review'],['tracker','views']]){await go(route('ja',page)+'?from=qa#'+anchor);await p.evaluate(()=>localStorage.setItem('hanji-knowledge-language','ko'));await p.click('.lang-picker summary');await wait(180);await Promise.all([p.waitForNavigation({waitUntil:'load'}),p.click('.lang-picker a[lang=fr]')]);assert.equal(new URL(p.url()).pathname,route('fr',page));assert(p.url().endsWith('?from=qa#'+anchor));assert(await p.$('#'+anchor));assert.equal(await p.$eval('.family-brand',e=>new URL(e.href).pathname),route('fr','lab'));console.log(page,'language switch retains page, real anchor, query; explicit French wins');}
 await p.setViewport({width:1440,height:1000});await go('/projects/knowledge/');await p.click('#merge');assert(await p.$eval('#merged-line',e=>!e.hidden));await p.click('#reset');assert(await p.$eval('#merged-line',e=>e.hidden));await p.click('.family-projects summary');await p.click('.theme-picker summary');await p.keyboard.press('Escape');assert(await p.$eval('.family-projects',e=>e.open));assert(await p.$eval('.theme-picker',e=>!e.open));await p.keyboard.press('Escape');assert(await p.$eval('.family-projects',e=>!e.open));console.log('Knowledge merge/reset and nested Escape preserved');
 await go('/projects/tracker/');await p.$eval('.tracker-mini',e=>e.scrollIntoView({block:'center',behavior:'instant'}));for(const n of [0,1,2,3,6,3,0,6]){await p.click(`[data-story-step="${n}"]`);assert.equal(await p.$eval('.tracker-mini',e=>e.dataset.running),'false');}await p.click('[data-story-toggle]');await wait(600);await p.click('[data-story-toggle]');await wait(2100);assert.equal(await p.$eval('.tracker-mini',e=>e.dataset.stage),'request');assert.equal(await p.$eval('[data-story-toggle]',e=>e.textContent),'Resume');await p.click('[data-story-toggle]');await wait(1800);assert.equal(await p.$eval('.tracker-mini',e=>e.dataset.stage),'project');await p.click('[data-story-restart]');await p.focus('[data-story-toggle]');await p.keyboard.press('Escape');assert.equal(await p.$eval('.tracker-mini',e=>e.dataset.running),'false');await p.click('[data-story-restart]');await p.waitForFunction(()=>document.querySelector('.tracker-mini').dataset.stage==='done',{timeout:20000});assert.equal((await p.$$('.tm-card[data-state=review]')).length,4);console.log('Repeated manual steps, replay, interrupted pause/resume, Escape, full sequence passed');await p.click('[data-story-restart]');await p.evaluate(()=>scrollTo({top:document.body.scrollHeight,behavior:'instant'}));await p.waitForFunction(()=>document.querySelector('.tracker-mini').dataset.running==='false');console.log('Offscreen animation pauses');await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);await p.waitForFunction(()=>document.querySelector('.tracker-mini').dataset.stage==='done');assert(await p.$eval('.illustration-summary',e=>getComputedStyle(e).position==='static'));assert.equal(await p.$eval('.tm-card',e=>getComputedStyle(e).transitionDuration),'0s');console.log('Reduced motion settles to complete story with readable summary');await go('/ko/projects/tracker/');assert.equal(await p.$eval('[data-story-toggle]',e=>e.textContent),'다시 보기');console.log('Localized animation controls passed');
 assert.deepEqual(errors,[],'No browser runtime errors');assert.deepEqual(missing,[],'No missing local assets');console.log('PASS: full browser validation');
} finally {await browser.close();await new Promise(r=>server.close(r));}
