import puppeteer from 'puppeteer-core';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,existsSync,mkdirSync} from 'node:fs';
import path from 'node:path';
const types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2','.xml':'application/xml'};
const server=createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),file=path.join(process.cwd(),'dist',decodeURIComponent(u.pathname),u.pathname.endsWith('/')?'index.html':'');try{const body=readFileSync(file);res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(body);}catch{res.writeHead(404);res.end('Not found');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`;
const executablePath=process.env.BROWSER_EXECUTABLE||['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome','/usr/bin/google-chrome','/usr/bin/chromium'].find(existsSync);
assert(executablePath,'Set BROWSER_EXECUTABLE to an installed Chrome/Chromium.');
const browser=await puppeteer.launch({executablePath,headless:true});
const p=await browser.newPage();const errors=[],missing=[];
p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().startsWith(origin)&&r.status()>=400)missing.push(r.url());});
const go=route=>p.goto(origin+route,{waitUntil:'load'}),wait=ms=>new Promise(r=>setTimeout(r,ms));
const langs=['en','ko','de','ja','fr'],pages=['lab','knowledge','tracker'];
const route=(l,page)=>l==='en'?(page==='lab'?'/':`/projects/${page}/`):page==='lab'?`/${l}/lab/`:`/${l}/projects/${page}/`;
const out=process.env.QA_OUTPUT||'test-results';mkdirSync(out,{recursive:true});
await p.setCacheEnabled(false);
await p.setRequestInterception(true);
p.on('request',r=>r.url().endsWith('.woff2')?setTimeout(()=>r.continue(),500):r.continue());
const nav=()=>p.evaluate(()=>[...document.querySelectorAll('.family-brand,.family-shortcuts a,.theme-picker>summary,.lang-picker>summary')].map(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return {tag:e.tagName,font:s.fontFamily,weight:s.fontWeight,line:s.lineHeight,spacing:s.letterSpacing,width:Math.round(r.width*100)/100,x:Math.round(r.x*100)/100,y:Math.round(r.y*100)/100,height:Math.round(r.height*100)/100,stroke:e.querySelector('path')?getComputedStyle(e.querySelector('path')).strokeWidth:null};}));
try{
 for(const width of [1440,390]){await p.setViewport({width,height:1000});for(const l of langs){const samples=[];for(const page of pages){await p.goto(origin+route(l,page),{waitUntil:'domcontentloaded'});const early=await nav();await p.evaluate(()=>document.fonts.ready);await wait(100);const settled=await nav();assert.deepEqual(settled,early,`${width}/${l}/${page} font-load geometry`);samples.push(settled);await p.hover('.lang-picker summary');assert.deepEqual(await nav(),settled,'Hover has no geometry change');await p.click('.lang-picker summary');await wait(180);assert.deepEqual(await nav(),settled,'Open state has no text or geometry change');assert.equal(await p.$eval('.lang-picker .setting-icon',e=>getComputedStyle(e).width),'18px');await p.keyboard.press('Escape');if(l==='en'){await p.evaluate(()=>document.activeElement.blur());await (await p.$('.site-header')).screenshot({path:path.join(out,`nav-${page}-${width}.png`)});}console.log(width,l,page,'font/hover/open geometry stable');}assert.deepEqual(samples[0],samples[1],`${width}/${l}: lab vs Knowledge navbar`);assert.deepEqual(samples[0],samples[2],`${width}/${l}: lab vs Tracker navbar`);console.log(width,l,'all three navbars match exactly');}}
 await p.setViewport({width:1440,height:1000,isMobile:false,hasTouch:false});
 for(const page of ['knowledge','tracker']){
  await go(route('en',page));await p.evaluate(()=>document.fonts.ready);const scene=page==='knowledge'?'.mini-hanji':'.tracker-mini',paper=page==='knowledge'?'.mini-window':'.tracker-mini-window';await p.$eval(scene,e=>e.scrollIntoView({block:'center',behavior:'instant'}));await p.mouse.move(0,0);await wait(500);const base=await p.$eval(paper,e=>getComputedStyle(e).transform);const r=await p.$eval(scene,e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}});await p.mouse.move(r.x+r.width*.8,r.y+r.height*.3);await wait(500);const tilt=await p.$eval(paper,e=>({x:e.style.getPropertyValue('--tilt-x'),y:e.style.getPropertyValue('--tilt-y'),right:e.style.getPropertyValue('--edge-right'),transform:getComputedStyle(e).transform}));assert(Math.abs(parseFloat(tilt.x)-1.6)<.1);assert(Math.abs(parseFloat(tilt.y)-3)<.1);assert.notEqual(tilt.transform,base);await p.mouse.move(0,0);await wait(500);assert.equal(await p.$eval(paper,e=>e.style.getPropertyValue('--tilt-x')),'');assert.equal(await p.$eval(paper,e=>getComputedStyle(e).transform),base);await p.mouse.move(r.x+r.width*.8,r.y+r.height*.3);await p.keyboard.press('Tab');assert.equal(await p.$eval(paper,e=>e.style.getPropertyValue('--tilt-x')),'');console.log(page,'shared tilt: same geometry, dynamic edge, pointer leave and keyboard reset');
 }
 // Conversation continuity and edge geometry are covered by test:tracker-hero.
 for(const page of ['knowledge','tracker']){await go(route('en',page));const scene=page==='knowledge'?'.mini-hanji':'.tracker-mini',paper=page==='knowledge'?'.mini-window':'.tracker-mini-window';await p.$eval(scene,e=>e.scrollIntoView({block:'center',behavior:'instant'}));await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);await wait(100);await p.$eval(scene,e=>e.dispatchEvent(new PointerEvent('pointermove',{clientX:600,clientY:200,pointerType:'mouse'})));assert.equal(await p.$eval(paper,e=>e.style.getPropertyValue('--tilt-y')),'');if(page==='tracker'){assert.equal(await p.$eval('.tracker-mini',e=>e.dataset.stage),'done');assert.equal(await p.$eval('.illustration-summary',e=>getComputedStyle(e).position),'static');}await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'no-preference'}]);}console.log('Both papers: reduced motion prevents tilt; Tracker settles complete');
 await p.setViewport({width:390,height:1000,isMobile:true,hasTouch:true});for(const page of ['knowledge','tracker']){await go(route('en',page));const scene=page==='knowledge'?'.mini-hanji':'.tracker-mini',paper=page==='knowledge'?'.mini-window':'.tracker-mini-window';await p.$eval(scene,e=>e.dispatchEvent(new PointerEvent('pointermove',{clientX:300,clientY:200,pointerType:'touch'})));assert.equal(await p.$eval(paper,e=>e.style.getPropertyValue('--tilt-y')),'');}console.log('Both papers: touch/coarse pointers never tilt');assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('PASS: systemic consistency checks');
}finally{await browser.close();await new Promise(r=>server.close(r));}
