import puppeteer from 'puppeteer-core';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,existsSync,mkdirSync} from 'node:fs';
import path from 'node:path';
const types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2','.xml':'application/xml'};
const server=createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),file=path.join(process.cwd(),'dist',decodeURIComponent(u.pathname),u.pathname.endsWith('/')?'index.html':'');try{const body=readFileSync(file);res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(body);}catch{res.writeHead(404);res.end('Not found');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`;
const executablePath=process.env.BROWSER_EXECUTABLE||['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome','/usr/bin/google-chrome','/usr/bin/chromium'].find(existsSync);
assert(executablePath,'Set BROWSER_EXECUTABLE to an installed Chrome/Chromium.');
const browser=await puppeteer.launch({executablePath,headless:true});
const p=await browser.newPage();const errors=[],missing=[];
p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().startsWith(origin)&&r.status()>=400)missing.push(r.url());});
const go=route=>p.goto(origin+route,{waitUntil:'load'}),wait=ms=>new Promise(r=>setTimeout(r,ms));
const langs=['en','ko','de','ja','fr'],pages=['lab','knowledge','tracker'];
const route=(l,page)=>l==='en'?(page==='lab'?'/':`/projects/${page}/`):page==='lab'?`/${l}/lab/`:`/${l}/projects/${page}/`;
const out=process.env.QA_OUTPUT||'test-results';mkdirSync(out,{recursive:true});
const samples=[1120,2700,4000,4592,5040];
const styles=()=>p.evaluate(()=>{const selectors=['.mini-written.line-one','.mini-written.line-two','.mini-proposed','.mini-add.add-one','.mini-add.add-two','.mini-reviewed','.mini-merge','.merge-before','.merge-after','.cursor-ada','.cursor-claude','.cursor-codex'];return selectors.map(selector=>{const s=getComputedStyle(document.querySelector(selector));return {selector,opacity:s.opacity,clip:s.clipPath,transform:s.transform,left:s.left,top:s.top,background:s.backgroundColor};});});
try{
 // With scripts disabled the preserved CSS owns the original animation.
 // Compare it with the controlled version, without depending on another server.
 await p.setJavaScriptEnabled(false);await p.setViewport({width:1440,height:1000});await go('/projects/knowledge/');await p.evaluate(()=>document.fonts.ready);const originals=[];for(const time of samples){await p.evaluate(time=>document.querySelector('.mini-window').getAnimations({subtree:true}).forEach(a=>{a.pause();a.currentTime=time;}),time);originals.push(await styles());}
 await p.setJavaScriptEnabled(true);await go('/projects/knowledge/');await p.evaluate(()=>document.fonts.ready);assert.equal(await p.$eval('.mini-hanji',e=>e.dataset.managedMotion),'true');for(let i=0;i<5;i++){await p.click(`[data-story-step="${i}"]`);assert.equal(await p.$eval('.mini-hanji',e=>e.dataset.running),'false');assert.deepEqual(await styles(),originals[i],`Original keyframe appearance at ${samples[i]}ms`);}console.log('All five Knowledge snapshots match original CSS-driven appearance exactly');
 for(const width of [1440,390,320]){await p.setViewport({width,height:1000});for(const l of langs)for(const product of ['knowledge','tracker']){await go(route(l,product));const scene=product==='knowledge'?'.mini-hanji':'.tracker-mini';assert.equal(await p.$$eval('.illustration-step',es=>es.length),5);assert(await p.$eval('.illustration-controls',e=>!!e.getAttribute('aria-label')));assert(await p.$$eval('.illustration-step',es=>es.every(e=>e.getAttribute('aria-label').length>3)));await p.$eval(scene,e=>e.scrollIntoView({block:'center',behavior:'instant'}));await wait(150);assert.equal(await p.$eval(scene,e=>e.dataset.running),'true');await p.click('[data-story-toggle]');const time=await p.$eval(scene,e=>e.dataset.playhead);await wait(180);assert.equal(await p.$eval(scene,e=>e.dataset.playhead),time);await p.focus('[data-story-restart]');await p.keyboard.press('Enter');await wait(150);assert.equal(await p.$eval(scene,e=>e.dataset.running),'true');await p.focus('[data-story-toggle]');await p.keyboard.press('Space');assert.equal(await p.$eval(scene,e=>e.dataset.running),'false');assert(await p.$eval('.illustration-controls',e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth}));if(l==='en'&&width===390)await(await p.$(scene)).screenshot({path:path.join(out,`controls-${product}.png`)});console.log(width,l,product,'localized controls, autoplay, pause, keyboard replay and bounds pass');}}
 await go('/projects/knowledge/');await p.click('[data-story-restart]');await p.waitForFunction(()=>+document.querySelector('.mini-hanji').dataset.cycles>=1,{timeout:9000});const seen=new Set();for(let i=0;i<30;i++){await wait(200);seen.add(await p.$eval('.illustration-step[aria-pressed=true]',e=>e.dataset.storyStep));}assert.equal(seen.size,5);console.log('Knowledge loops continuously and all five dots follow the playhead');
 for(const product of ['knowledge','tracker']){await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);await go(route('en',product));const scene=product==='knowledge'?'.mini-hanji':'.tracker-mini';assert.equal(await p.$eval(scene,e=>e.dataset.running),'false');await p.click('[data-story-restart]');await p.click('[data-story-toggle]');assert.equal(await p.$eval(scene,e=>e.dataset.running),'false');if(product==='knowledge'){assert.equal(await p.$eval('.merge-after',e=>getComputedStyle(e).opacity),'1');await p.click('[data-story-step="0"]');assert.equal(await p.$eval('.mini-hanji',e=>e.dataset.playhead),'1120');}await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'no-preference'}]);}
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('PASS: shared illustration controls and reduced-motion snapshots');
}finally{await browser.close();await new Promise(r=>server.close(r));}
